baseURL       = "http://lauraonetwo.github.io/"
languageCode  = "en-us"
title         = "lauraonetwo"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 2
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 4
  # [[menu.nav]]
  #   name    = "Get in touch"
  #   url     = "contact"
  #   weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  logo_footer = "images/logo-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "lauraonetwo"
  author = "Laura Wang Qiu"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Reason"
    placeholder_about_the_project = "Some text..."
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "vd"
      title  = "Videogame Development"
    [[params.contactForm.projectType]]
      value = "sd"
      title  = "Software Development"
    [[params.contactForm.projectType]]
      value = "ud"
      title  = "UI/UX Design"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Laura Wang Qiu"
    tagline               = "@lauraonetwo"
    primary_button        = "See my projects"
    primary_button_url    = "portfolio"
    secondary_button      = "See my blog"
    secondary_button_url  = "blog"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "MY RECENT PROJECTS"
    subtitle  = "[Description]"
    view_project = "view project"
    more_works = "MORE PROJECTS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S CONNECT"
    primary_button      = "Contact"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Madrid, Spain"
      email   = "lauraonetwo443@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "#"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "I help companies:"
        description = "develop quality code<br>develop design solutions<br>manage projects"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
